/**
 * @file   IPackageRepository.h
 * @brief  Abstract repository interface for Package persistence.
 *
 * @author Huynh Phuc Nguyen
 * @date   2026-06-11
 * 
 * @update
 * @author Do Minh Khang
 * @date   2026-07-16
 * @changelog
 *   - Added findByCriteria(const PackageQueryCriteria&) so filtering can be
 *     pushed into the backing store (SQL WHERE clause) instead of always
 *     fetching everything via getAll() and filtering in C++.
 * 
 * Design rules:
 *  - Pure C++ interface; no Qt, no JSON, no file I/O.
 *  - All methods operate on the domain type Package.
 *  - Concrete implementations (JsonPackageRepository, etc.) live in
 *    separate .h/.cpp files and may use Qt or third-party libs.
 */

#pragma once

#include "domain/entities/Package.h"
#include "domain/queries/PackageQueryCriteria.h"

#include <string>
#include <vector>
#include <optional>

namespace wms::repository
{
    /**
     * @interface IPackageRepository
     * @brief     CRUD contract for package storage.
     *
     * Services depend only on this interface, never on a concrete class,
     * enabling easy substitution (JSON file, SQLite, REST API, etc.).
     */
    class IPackageRepository
    {
    public:
        virtual ~IPackageRepository() = default;

        // --Read--

        /**
         * @brief  Retrieve all packages currently in the repository.
         * @return A vector of Package copies; empty if the store is empty.
         */
        virtual std::vector<domain::Package> getAll() const = 0;

        /**
         * @brief  Retrieve a single package by its UUID.
         * @param  id  UUID string as generated by Package.
         * @return The package if found; std::nullopt otherwise.
         */
        virtual std::optional<domain::Package> getById(const std::string& id) const = 0;

        // --Write--

        /**
         * @brief  Persist a new package.
         *
         *  The package must not already exist (checked by id). If it does,
         *  implementations should throw std::runtime_error.
         *
         * @param  package  The package to add (passed by value; will be moved).
         */
        virtual void add(domain::Package package) = 0;

        /**
         * @brief  Replace the stored package that matches package.id().
         *
         *  If no package with that id exists, implementations should throw
         *  std::runtime_error.
         *
         * @param  package  Updated package (passed by value; will be moved).
         */
        virtual void update(domain::Package package) = 0;

        /**
         * @brief  Remove a package from the repository.
         * @param  id  UUID of the package to remove.
         * @throws std::runtime_error if the id is not found.
         */
        virtual void remove(const std::string& id) = 0;

        // --Persistence--

        /**
         * @brief  Flush all in-memory changes to the backing store (file, DB, …).
         *
         *  For in-memory-only implementations this is a no-op.
         */
        virtual void save() = 0;

        /**
         * @brief  Reload all data from the backing store, discarding in-memory state.
         */
        virtual void load() = 0;

        // --Query--

        /**
         * @brief  Query packages matching every set field of @p criteria.
         *
         *  Replaces one-method-per-filter (findByState, findByZone,...) 
         *  with a single entry point. Concrete implementations decide how
         *  to evaluate this - a SQL-backed repository should translate
         *  it into a parameterised WHERE clause so the database's indexes
         *  do the filtering; a JSON-backed repository evaluates it against
         *  its in-memory store. Either way, callers get identical
         *  semantics: an empty/default-constructed criteria matches every
         *  package, equivalent to getAll().
         *
         * @param  criteria  Filter fields; unset fields are not constrained.
         * @return All matching packages, order not guaranteed - callers
         *         that need a stable order should sort the result.
         */
        virtual std::vector<domain::Package> findByCriteria(
            const domain::PackageQueryCriteria& criteria) const = 0;
    };
}
